In [13]:
from IPython.core.display import HTML
# Apply styles globally within the notebook
HTML('''
<style>
  h2 {
    font-size: var(--j3p-content-font-size4);
    background-color:#00FF00  ;
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 10px 41px;
    top: 10px;
    position: relative;
    border-radius: 10px 50px 10px 50px;
}

 img {       /* flex-grow: 1; */
            /* flex-shrink: 1; */
            border-radius: 100px 70px 150px 70px; 
            border: 10px solid #eee;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: box-shadow 0.3s ease; /* Add a transition for a smooth effect */
        }

       img:active {
          box-shadow: 0 10px 20px rgba(255, 255, 0, 0.5), 0 6px 6px rgba(215, 215, 0, 0.5);
        }
</style>
''') 

In [11]:
import numpy as np
import pandas as pd


In [6]:
i=[1,2,3,4]
print(np.shape(i))

(4,)


In [10]:
v=[3,1]
print(np.shape(v))

(2,)


## Numpy :

In [14]:
import numpy as np 


In [15]:
a=np.array([1,2,3,4,5])
print(a);print(np.shape(a))

[1 2 3 4 5]
(5,)


In [17]:
c=np.zeros([2,2])
c

array([[0., 0.],
       [0., 0.]])

In [23]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [30]:
# reshape :

np.arange(2,14).reshape(3,4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

## Differnce between matrix & Vector & tensor :

In [36]:
s=np.array([100,5,10])
print(np.shape(s))
m=np.array([[10,15,12],[15,20,100]])
print(np.shape(m))

(3,)
(2, 3)


In [39]:
t=np.array([[[5,10],[2,100]],[[6,9],[10,5]],[[0,200],[1000,250]]])
t.shape

(3, 2, 2)

## Broadcasting :

In [41]:
a=np.array([3,2,3,4])
b=np.array([10,15,20,100])
c=a*b
c

array([ 30,  30,  60, 400])

In [42]:
np.dot(a,b) # dot proudct

520

In [46]:
b1=np.array([[1,2,3],[5,6,7],[9,10,11]])
b2=np.array([100,10,15])
print(b1+b2)

[[101  12  18]
 [105  16  22]
 [109  20  26]]
