In [1]:
from IPython.core.display import HTML

# Apply styles globally within the notebook

HTML('''
<style>
  h2 {
    font-size: var(--j3p-content-font-size4);
    background-color:#00FF00  ;
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 10px 41px;
    top: 10px;
    position: relative;
    border-radius: 10px 50px 10px 50px;
}

 img {       /* flex-grow: 1; */
            /* flex-shrink: 1; */
            border-radius: 100px 70px 150px 70px; 
            border: 10px solid #eee;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: box-shadow 0.3s ease; /* Add a transition for a smooth effect */
        }

       img:active {
          box-shadow: 0 10px 20px rgba(255, 255, 0, 0.5), 0 6px 6px rgba(215, 215, 0, 0.5);
        }
</style>
''') 

<img src="Neuro.jpg" alt="My Image">

## Created By  : Eng/AbdalRhman Gameel Ahmed Hebishy 


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>&bull;  AbdalRhman Hebishy , DataScientist||Machine learning||Deeplearning Engineer .</p>

<p>&bull; <a href="https://www.kaggle.com/abdalrhamnhebishy" target="_blank">Kaggle profile</a>.</p>

<p>&bull; <a href="https://github.com/AbdalRahmna" target="_blank">Github profile</a>.</p>

<p>&bull; <a href="https://www.linkedin.com/in/abdalrahman-hebishy-06465b254/"_blank">linkedin profile</a>.</p>


</div>


In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>1. Array Creation:
 - Write a NumPy code to create a 2D array of shape (4, 5) filled with random integers between
10 and 50.</p>



</div>

In [3]:
array_2d = np.random.randint(10, 51, size=(4, 5)) 
print("2D Array (4, 5) filled with random integers between 10 and 50:",array_2d)


2D Array (4, 5) filled with random integers between 10 and 50: [[20 18 35 50 49]
 [50 39 43 44 45]
 [26 18 13 28 27]
 [43 43 10 48 18]]


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p> - Create a 1D NumPy array of 20 evenly spaced values between 0 and 5.</p>

</div>


In [4]:
array_1d = np.linspace(0, 5, num=20)
print("\n1D Array of 20 evenly spaced values between 0 and 5:",array_1d)


1D Array of 20 evenly spaced values between 0 and 5: [0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>2. Array Manipulation:
 - Given a 2D array `arr`, write a code to swap the first and last rows.
 - How would you flatten a 3D array into a 1D array using NumPy? </p>

</div>


In [5]:

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print("Original Array:")
print(arr)

# Swap the first and last rows
arr[[0, -1]] = arr[[-1, 0]]

print("\nArray after swapping the first and last rows:")
print(arr)

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Array after swapping the first and last rows:
[[16 17 18 19 20]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 1  2  3  4  5]]


In [6]:
# Create a sample 3D array (for demonstration)
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                      [[7, 8, 9], [10, 11, 12]]])

print("Original 3D Array:")
print(array_3d)

# Flatten the 3D array into a 1D array using flatten()
flattened_array = array_3d.flatten()
print("\nFlattened 1D Array using flatten():")
print(flattened_array)

flattened_array_ravel = array_3d.ravel()
print("\nFlattened 1D Array using ravel():")
print(flattened_array_ravel)

Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flattened 1D Array using flatten():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Flattened 1D Array using ravel():
[ 1  2  3  4  5  6  7  8  9 10 11 12]


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>3. Array Indexing:
 - Write a code to extract all elements from a NumPy array that are greater than a specified
value. </p>

</div>


In [7]:

array = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])
specified_value = 25
extracted_elements = array[array > specified_value]

print(f"Original Array: {array}")
print(f"Elements greater than {specified_value}: {extracted_elements}")

Original Array: [10 15 20 25 30 35 40 45 50]
Elements greater than 25: [30 35 40 45 50]


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p> - Given a 2D array, write a code to extract a subarray that contains only the second and third
columns. </p>

</div>


In [8]:

array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])

print("Original Array:")
print(array_2d)

# Extract the second and third columns (index 1 and 2)
subarray = array_2d[:, 1:3]

print("\nSubarray containing the second and third columns:")
print(subarray)

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Subarray containing the second and third columns:
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>4. Mathematical Operations:</p>
<p>  - Write a NumPy code to normalize a 1D array so that its values range between 0 and 1</p>

</div>


In [9]:
array_1d = np.array([10, 15, 20, 25, 30, 35, 40])
print("Original Array:",array_1d)

# Normalize the array
min_value = np.min(array_1d)
max_value = np.max(array_1d)
normalized_array = (array_1d - min_value) / (max_value - min_value)

print("\nNormalized Array (values between 0 and 1):")
print(normalized_array)

Original Array: [10 15 20 25 30 35 40]

Normalized Array (values between 0 and 1):
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>  - Create a code that calculates the dot product of two matrices using NumPy. </p>

</div>


In [10]:
matrix_a = np.array([[1, 2, 3],
                      [4, 5, 6]])

matrix_b = np.array([[7, 8],
                      [9, 10],
                      [11, 12]])

dot_product = np.dot(matrix_a, matrix_b)
print("\nDot Product of Matrix A and Matrix B:")
print(dot_product)


Dot Product of Matrix A and Matrix B:
[[ 58  64]
 [139 154]]


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p> 5. Statistical Operations:
 - Write a code to calculate the mean, median, and standard deviation of a NumPy array </p>

</div>


In [11]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Calculate the mean
mean_value = np.mean(data)

# Calculate the median
median_value = np.median(data)

# Calculate the standard deviation
std_deviation = np.std(data)


print("Data Array:")
print(data)
print(f"\nMean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_deviation}")

Data Array:
[10 20 30 40 50 60 70 80 90]

Mean: 50.0
Median: 50.0
Standard Deviation: 25.81988897471611


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>  - Given an array of values, how would you find the most frequent value using NumPy? </p>

</div>


In [12]:
data = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5, 6, 7, 8, 8, 8, 8])

unique_values, counts = np.unique(data, return_counts=True)

# Find the index of the maximum count
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[most_frequent_index]

print(f"\nMost Frequent Value: {most_frequent_value}")


Most Frequent Value: 5


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>6. DataFrame Creation:
 - Write a pandas code to create a DataFrame from a dictionary with lists. Each key in the
dictionary should represent a column. </p>

</div>


In [13]:

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 30, 22, 35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

print("DataFrame created from dictionary:\n",df)


DataFrame created from dictionary:
       Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p> - Create a pandas DataFrame from a CSV file, and display the first 10 rows. </p>

</div>



In [14]:
df = pd.read_csv('insurance.csv')
df.head(10)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">

<p>7. DataFrame Manipulation:
 - Given a DataFrame, write a code to rename columns and drop any rows with missing values. </p>

</div>

In [15]:
# Rename columns
df.rename(columns={'age': 'Age (Years)', 'sex': 'Gender'}, inplace=True)

# Drop rows with missing values
df.dropna(inplace=True)

df

Age (Years)  Gender     bmi  children smoker     region      charges
0              19  female  27.900         0    yes  southwest  16884.92400
1              18    male  33.770         1     no  southeast   1725.55230
2              28    male  33.000         3     no  southeast   4449.46200
3              33    male  22.705         0     no  northwest  21984.47061
4              32    male  28.880         0     no  northwest   3866.85520
...           ...     ...     ...       ...    ...        ...          ...
1333           50    male  30.970         3     no  northwest  10600.54830
1334           18  female  31.920         0     no  northeast   2205.98080
1335           18  female  36.850         0     no  southeast   1629.83350
1336           21  female  25.800         0     no  southwest   2007.94500
1337           61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [16]:
df["age+children+bmi"]=df["Age (Years)"]+df["children"]+df["bmi"]
df

Age (Years)  Gender     bmi  children smoker     region      charges  \
0              19  female  27.900         0    yes  southwest  16884.92400   
1              18    male  33.770         1     no  southeast   1725.55230   
2              28    male  33.000         3     no  southeast   4449.46200   
3              33    male  22.705         0     no  northwest  21984.47061   
4              32    male  28.880         0     no  northwest   3866.85520   
...           ...     ...     ...       ...    ...        ...          ...   
1333           50    male  30.970         3     no  northwest  10600.54830   
1334           18  female  31.920         0     no  northeast   2205.98080   
1335           18  female  36.850         0     no  southeast   1629.83350   
1336           21  female  25.800         0     no  southwest   2007.94500   
1337           61  female  29.070         0    yes  northwest  29141.36030   

      age+children+bmi  
0               46.900  
1               52.770  
2               64.000  
3               55.705  
4               60.880  
...                ...  
1333            83.970  
1334            49.920  
1335            54.850  
1336            46.800  
1337            90.070  

[1338 rows x 8 columns]

<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">
<p> - How would you add a new column to a DataFrame that contains the cumulative sum of
another column?</p>
</div>

In [17]:
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50]
}
df = pd.DataFrame(data)
df['Cumulative_Sum'] = df['A'].cumsum()
df

A   B  Cumulative_Sum
0  1  10               1
1  2  20               3
2  3  30               6
3  4  40              10
4  5  50              15

<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">
<p>8. Filtering and Selection:
 - Write a code to filter rows in a DataFrame where a specific column's value is greater than
100.</p>
</div>

In [20]:

data = {
    'Product': ['A', 'B', 'C', 'D', 'E'],
    'Sales': [150, 80, 200, 50, 120],
    'Quantity': [10, 5, 15, 7, 8]
}

df = pd.DataFrame(data)

# Filter rows where the 'Sales' column is greater than 100
filtered_df = df[df['Sales'] > 100]
print(filtered_df)

  Product  Sales  Quantity
0       A    150        10
2       C    200        15
4       E    120         8


<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">
<p> - How would you select specific rows and columns from a DataFrame using `.loc` and `.iloc`?</p>
</div>

In [25]:
df.loc[0]

Product       A
Sales       150
Quantity     10
Name: 0, dtype: object

<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">
<p>9. Handling Missing Data:
 - Write a code to replace all missing values in a DataFrame with the mean of their respective
columns.</p>
</div>

In [27]:
data = {
    'A': [1, 2, np.nan, 4],
    'B': [10, np.nan, 30, 40],
    'C': [np.nan, 200, 300, 400]
}

df = pd.DataFrame(data)

# Calculate the mean of each column and replace missing values with the mean
df.fillna(df.mean(), inplace=True)

print("\nDataFrame after replacing missing values with column means:")
print(df)


DataFrame after replacing missing values with column means:
          A          B      C
0  1.000000  10.000000  300.0
1  2.000000  26.666667  200.0
2  2.333333  30.000000  300.0
3  4.000000  40.000000  400.0


In [28]:
df.isna().mean()

A    0.0
B    0.0
C    0.0
dtype: float64

<div style="border: 5px solid yellow; padding: 10px; background-color: #F5F5DC; color: blue; border-radius: 30px 45px 30px 45px;">
<p>- How would you drop columns in a DataFrame that contain more than 50% missing values?</p>
</div>

In [29]:
data = {
    'A': [1, 2, np.nan, 4],
    'B': [10, np.nan, 30, 40],
    'C': [np.nan, 200, 300, 400],
    'D': [np.nan, np.nan, np.nan, np.nan]
}

df = pd.DataFrame(data)

# Set the threshold :
threshold = 0.5

missing_percent = df.isnull().mean()

# Drop columns where the percentage of missing values is greater than the threshold
df = df.loc[:, missing_percent < threshold]

print("\nDataFrame after dropping columns with more than 50% missing values:")
print(df)


DataFrame after dropping columns with more than 50% missing values:
     A     B      C
0  1.0  10.0    NaN
1  2.0   NaN  200.0
2  NaN  30.0  300.0
3  4.0  40.0  400.0


<img src="https://img.freepik.com/free-vector/lettering-design-with-positive-message_23-2149008842.jpg" alt="My Image">